export const ADMIN_STATUS = {
  UNVERIFIED: "UNVERIFIED",
  PHONE_VERIFIED: "PHONE_VERIFIED",
  VERIFIED: "VERIFIED"
};

export const ADMIN_STATUS_CHANGE_LOG = {
  ACTIVATED: "ACTIVATED",
  DEACTIVATED: "DEACTIVATED"
};

export const ADMIN_RESET_PASSWORD_STATUS = {
  EMPTY: "",
  REQUESTED: "REQUESTED",
  PHONE_VERIFIED: "PHONE_VERIFIED",
  EMAIL_VERIFIED: "EMAIL_VERIFIED",
  COMPLETED: "COMPLETED"
};
