export const VERIFICATION_STATUS = {
  UNVERIFIED: 'UNVERIFIED',
  PHONE_VERIFIED: 'PHONE_VERIFIED',
  VERIFIED: 'VERIFIED'
};

export const USER_ROLES = {
  ADMIN: 'ADMIN',
  TEACHER: 'TEACHER',
  PARENT: 'PARENT',
  STUDENT: 'STUDENT',
  SUPER_ADMIN: 'SUPER_ADMIN'
};