export const FEE_FREQUENCY = {
  MONTHLY: "MONTHLY",
  QUARTERLY: "QUARTERLY",
  BY_MONTHLY: "BY_MONTHLY",
  HALF_YEARLY: "HALF_YEARLY",
  YEARLY: "YEARLY"
};

export const FEE_STRUCTURE_STATUS = {
  DRAFT: "DRAFT",
  ACTIVE: "ACTIVE"
};
