export const LEAVE_REQUEST_STATUS = {
  ACCEPT: "ACCEPT",
  REJECT: "REJECT",
  PENDING: "PENDING",
  COMPLETE: "COMPLETE",
  EXPIRED: "EXPIRED"
};

export const LEAVE_SENDER_MODEL = {
  TEACHER: "TEACHER",
  STUDENT: "STUDENT"
};

export const LEAVE_RECEIVER_MODEL = {
  ADMIN: "ADMIN",
  TEACHER: "TEACHER"
};
