export const OTP_TYPE = {
  PHONE_VERIFICATION: "PHONE_VERIFICATION",
  EMAIL_VERIFICATION: "EMAIL_VERIFICATION",
  FORGET_PASSWORD: "FORGET_PASSWORD"
};

export const OTP_MEDIUM = {
  SMS: "SMS",
  EMAIL: "EMAIL"
};

export const OTP_ENTITY_TYPE = {
  ADMIN: "ADMIN",
  TEACHER: "TEACHER",
  PARENT: "PARENT"
};

export const OTP_STATUS = {
  PENDING: "PENDING",
  VERIFIED: "VERIFIED",
  EXPIRED: "EXPIRED"
};
