export const PARENT_GENDER = {
  MALE: "MALE",
  FEMALE: "FEMALE",
  OTHER: "OTHER"
};

export const PARENT_STATUS = {
  UNVERIFIED: "UNVERIFIED",
  PHONE_VERIFIED: "PHONE_VERIFIED",
  VERIFIED: "VERIFIED"
};
