export const PASSWORD_CHANGE_REASON = {
  FORGET_PASSWORD: "FORGET_PASSWORD",
  CHANGE_DEVICE: "CHANGE_DEVICE",
  TECHNICAL: "TECHNICAL",
  OTHER: "OTHER"
};

export const PASSWORD_CHANGE_SENDER_MODEL = {
  TEACHER: "TEACHER",
  PARENT: "PARENT",
  ADMIN: "ADMIN"
};

export const PASSWORD_CHANGE_RECEIVER_MODEL = {
  ADMIN: "ADMIN",
  SUPER_ADMIN: "SUPER_ADMIN"
};

export const PASSWORD_CHANGE_STATUS = {
  ACCEPT: "ACCEPT",
  REJECT: "REJECT",
  PENDING: "PENDING",
  EXPIRED: "EXPIRED",
  COMPLETE: "COMPLETE"
};

export const PARENT_PASSWORD_CHANGE_STATUS = {
  PENDING: "PENDING",
  EXPIRED: "EXPIRED",
  COMPLETED: "COMPLETED"
};
