export const ENROLLMENT_STATUS = {
  NEW_ADMISSION: 'NEW_ADMISSION',
  PROMOTED: 'PROMOTED',
  FAILED: 'FAILED'
};

export const FEE_STATUS = {
  PENDING: 'PENDING',
  PARTIAL: 'PARTIAL',
  PAID: 'PAID'
};