export const TRANSFER_REQUEST_TYPE = {
  TRANSFER: "TRANSFER",
  MIGRATION: "MIGRATION",
  LEAVING: "LEAVING"
};

export const TRANSFER_REASON = {
  PARENT_TRANSFER: "PARENT_TRANSFER",
  FAMILY_RELOCATION: "FAMILY_RELOCATION",
  BETTER_OPPORTUNITY: "BETTER_OPPORTUNITY",
  FINANCIAL: "FINANCIAL",
  ACADEMIC: "ACADEMIC",
  DISCIPLINARY: "DISCIPLINARY",
  MEDICAL: "MEDICAL",
  OTHER: "OTHER"
};

export const CONDUCT_CHARACTER_RATING = {
  EXCELLENT: "EXCELLENT",
  VERY_GOOD: "VERY_GOOD",
  GOOD: "GOOD",
  SATISFACTORY: "SATISFACTORY",
  NEEDS_IMPROVEMENT: "NEEDS_IMPROVEMENT"
};

export const TRANSFER_STATUS = {
  SUBMITTED: "SUBMITTED",
  APPROVED_BY_PARENT: "APPROVED_BY_PARENT",
  REJECTED_BY_PARENT: "REJECTED_BY_PARENT",
  CERTIFICATE_ISSUED: "CERTIFICATE_ISSUED"
};
