export const  errors = {
  generic:{
    firstnameRequired:"first name is required",
    lastnameRequired:"first name is required",
    phonePattern: "invalid phone number",
    phoneLength:"phone no. should have 10 digits",
    phoneRequired:"phone no. is required",
    emailPattern: "invalid Email Id",
    emailRequired: "email is required",
    passwordPattern :"Password should contains alpha-numberic special symbols",
    passwordRequired:"password is required",
    address :"address is required",
    invalidEmail:"unauthorized user",
    invalidPassword:"unauthorized user",
    duplicateEmail : "email already exist",
    duplicatePhone : "phone number already registered",
    nameMinLength: "admin name should be atleast 5 chars long",
    nameMaxLength: "admin name length must be smaller than 15 chars",
    nameRequired: "admin name is required!",
    dobRequired:"date of birth is required.",
    bloodGroupRequired:"blood group is required.",
    genderRequired:"gender is required.",
    universityRequired:"university is required.",
    degreeRequired: "degree is required.",   
    jwtTokenRequired:"Authorization token is required!",
    successfullPasswordUpdate:"password updated successfully",

  },
  admin:{
    affiliationMinLength: "Affiliation no. should be atleast 5 chars long",
    affiliationMaxLength: "Affiliation no. length must be smaller than 50 chars",
    affiliationRequired: "Affiliation no. is required!",
    adminNotFound:"admin doesn't exists",
    duplicateName :"admin name already exist",
    duplicateAffiliation : "affiliation no. already exist",
    registerError:"admin couldn't be registered",
    successfullRegister:"admin registered successfully!",
  },
  teacher:{
    successfullRegister:"teacher created successfully!",
    notAssignedToSection:"teacher is not assigned to any section",
    notFound:"teacher doesn't exists",
    updateError:"teacher details cann't be updated",
    successfullUpdate:"teacher updated successfully",
    successfullDelete:"teacher deleted successfully", 
    notMatchToSection:"class teacher does not belong to this section",
  },
  student:{
    parentNameRequred:"parent name is required",
    duplicateStudent:"student already exists",
    registerError:"can't register student",
    successfullRegister:"student created successfully",
    successfullDelete:"student deleted successfully",
    successfullUpdate:"student deleted successfully",
    deleteError:"student can't deleted",
    updateError:"student can't updated",
  },
  section:{
    duplicateSection:"section name already exist",
    coordinatorNotFound:"cordinator doesn't exist",
    successfullRegister:"section created successfully!",
    notFound:"section doesn't exists",
    deleteError:"can't delete section",
    successfullDelete:"section deleted successfully",
  },
  parent:{
    successfullRegister:"parent registered successfully!",
    RegisterError:"parent can't registered !",
    notFound:"parent doesn't exists",
    UpdateError:"parent can't updated",
  },
  holidayEvent:{
    duplicateEvent:"holiday event already exists",
    RegisterError:"holiday event cann't be created",
    successfullRegister:"holiday event has been created sucessfully",
    notFound:"holiday event doesn't exists",
    successfullDelete:"event deleted successfully",
  },
  class:{
    duplicateClass:"class already exists",
    successfullRegister: "class registered successfully!",
    notFound:"class doesn't exists",
    deleteError: "can't delete class, there are sections.",
    successfulDelete:"class deleted successfully",
  },
  attendance:{
    sunday:"today is sunday",
    holiday:"today is scheduled as holiday!",
    invalidAttendance:"invalid attendance value",
    unauthorizedParent:"parent is not authorized to mark attendance.",
    parentUnabledToMarkAttendance:"parent can't mark attendance,teacher already marked.",
    alreadyMarkedByParent:"attendance already marked by parent",
    successfullyMarked:"attendance marked sucessfully",
    notMarked:"attendance haven't marked today",
    successfullyUpdated:"attendance updated successfully",
  }

}