# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code,
# run security scans with Trivy, and deploy the application.

name: Node.js CI DEV

on:
    push:
        branches: ['dev']

permissions:
    contents: read

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            # Step 1: Checkout the code
            - uses: actions/checkout@v7

            # Step 2: Setup Node.js environment
            - name: Use Node.js 24
              uses: actions/setup-node@v7
              with:
                  node-version: '24'
                  cache: 'npm'
                  cache-dependency-path: package-lock.json
            # Step 6: Security scan with Trivy
            - name: Run Trivy Security Scan
              uses: aquasecurity/trivy-action@master
              with:
                  scan-type: 'fs'          # Scans the filesystem
                  scan-ref: .         # Path to scan (project root)
                  format: 'table'          # Human-readable output
                  ignore-unfixed: true     # Ignore vulnerabilities without fixes
                  severity: 'HIGH,CRITICAL' # Scan for high-severity vulnerabilities only

            # Step 7: Deploy to Hostinger VPS
            - name: Deploy to Hostinger VPS 
              uses: appleboy/ssh-action@v1.2.0 
              with: 
                host: ${{ secrets.HOST }} 
                username: ${{ secrets.USERNAME }} 
                key: ${{ secrets.SSH_KEY }}
                script: | 
                  cd /root/var/www/dev/server 

                  echo "Fetching latest code..." 
                  git fetch origin 

                  echo "Switching to dev branch..." 
                  git checkout dev

                  echo "Updating repository..." 
                  git reset --hard origin/dev

                  mkdir bin
                  echo "${{ secrets.DEV }}" > bin/.env.dev

                  echo "Installing dependencies..." 
                  npm ci

                  echo "Reloading PM2..." 
                  if pm2 describe SIKSHA_BACKEND_DEV > /dev/null; then 
                      NODE_ENV=dev pm2 reload SIKSHA_BACKEND_DEV 
                  else 
                     NODE_ENV=dev pm2 start index.js --name SIKSHA_BACKEND_DEV 
                  fi 
                  pm2 save 
                  pm2 status
